/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   http-method-selector-mixin.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {dedupingMixin} from '@polymer/polymer/lib/utils/mixin.js';

import {afterNextRender} from '@polymer/polymer/lib/utils/render-status.js';

export {HttpMethodSelectorMixin};

declare namespace ArcMixins {


  /**
   * A behavior to share common code between both method selectors.
   */
  function HttpMethodSelectorMixin<T extends new (...args: any[]) => {}>(base: T): T & HttpMethodSelectorMixinConstructor;

  interface HttpMethodSelectorMixinConstructor {
    new(...args: any[]): HttpMethodSelectorMixin;
  }

  interface HttpMethodSelectorMixin {
    readonly standardMethods: any;

    /**
     * Currently selected HTTP method
     */
    method: string|null|undefined;

    /**
     * True if the request for selected HTTP method can carry a payload. It
     * is defined in HTTP spec.
     */
    readonly isPayload: boolean|null|undefined;

    /**
     * Set to true when the user opens the dropdown menu
     */
    methodMenuOpened: boolean|null|undefined;

    /**
     * When set it allows to render a custom method selector
     */
    renderCustom: boolean|null|undefined;

    /**
     * When set the editor is in read only mode.
     */
    readonly: boolean|null|undefined;
    _attachListeners(node: any): void;
    _detachListeners(node: any): void;

    /**
     * Compute if the tayload can carry a payload.
     */
    _computeIsPayload(method: any): any;

    /**
     * Handler for `isPayload` property change
     */
    _onIsPayloadChanged(value: any): void;

    /**
     * Handler for `method` property chnage
     */
    _methodChanged(method: any): void;

    /**
     * Responds to an event requesting status check for `isPayload` propery by setting the `value`
     * property on the event and canceling the event.
     */
    _isPayloadStatusHandler(e: CustomEvent|null): void;

    /**
     * If the event source is not this element it will update the method value.
     */
    _methodChangedHandler(e: CustomEvent|null): void;
    closeCustom(): void;

    /**
     * Checks if there is an empty method name and if it is it will set `renderCustom` property
     * that constrolls display of a custom method input.
     */
    _dropdownMenuOpened(opened: Boolean|null, method: String|null): void;
  }
}

export {HttpMethodSelectorMixinConstructor};
